version: '3'

services:

  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - ./data/static/trade.html:/usr/local/openresty/nginx/html/trade.html
      - ./etc/nginx:/etc/nginx/conf.d
      - ./etc/nginx/lua:/usr/local/openresty/nginx/html/lua
